const starterPlants = [
  {id:'lipstick', name:'Curly Lipstick Plant', botanical:'Aeschynanthus radicans', badge:'Easy-going', tags:['easy'], pos:'82%', icon:'⌇', care:{watering:'Water when the top inch of soil feels dry. Keep it lightly and evenly moist in its growing months, but never soggy.', fertilising:'Feed at half strength every 2–4 weeks while it is actively growing. Let a new plant settle in for 2–4 weeks first.', light:'Bright, indirect light keeps the curls full and helps flowers form. A little gentle morning sun is lovely.', soil:'An airy, fast-draining mix. Add orchid bark or perlite to regular houseplant soil.', spot:'Near an east-facing window, or just back from a bright south or west window.', watch:'Crispy leaves usually mean dry air or underwatering; yellow leaves usually mean it stayed too wet.'}},
  {id:'silver-crown', name:'Silver Crown Sansevieria', botanical:'Dracaena trifasciata', badge:'Very easy', tags:['easy'], pos:'65%', icon:'↟', care:{watering:'Let the potting mix dry out completely, then water thoroughly and let excess drain away. Much less often in winter.', fertilising:'A light feed every 6–8 weeks during active growth is plenty.', light:'Flexible and forgiving: low to bright indirect light. Brighter light encourages stronger growth.', soil:'Use a cactus or succulent mix, ideally with extra perlite for fast drainage.', spot:'A few feet from almost any window; avoid a cold, draughty sill.', watch:'Soft or yellowing leaves usually mean too much water. Keep water out of the center of the rosette.'}},
  {id:'turtles', name:'String of Turtles', botanical:'Peperomia prostrata', badge:'Gentle care', tags:['bright'], pos:'49%', icon:'◌', care:{watering:'Water when the upper half of the pot feels dry. Its fine roots dislike both bone-dry soil and sitting wet.', fertilising:'Half-strength feed every 4–6 weeks in the growing season.', light:'Bright, indirect light. Too much sun fades the tiny turtle pattern.', soil:'A small pot of airy, well-draining mix with perlite or bark.', spot:'A bright shelf near an east or filtered south-facing window.', watch:'Sparse vines can mean low light. Mushy stems are a sign to let the mix dry more between waterings.'}},
  {id:'bananas', name:'String of Bananas', botanical:'Curio radicans', badge:'Sun seeker', tags:['easy','bright'], pos:'32%', icon:'⌁', care:{watering:'Allow the soil to dry almost completely, then soak and drain. The banana-shaped leaves hold a little water.', fertilising:'Feed lightly every 4–6 weeks during active growth.', light:'Bright indirect light, with a few hours of gentle sun if it can take it.', soil:'A very fast-draining cactus or succulent blend in a pot with a drainage hole.', spot:'A sunny hanging spot, set just back from a south or west window.', watch:'Transparent or mushy bananas point to overwatering. Long gaps between leaves usually mean it wants more light.'}},
  {id:'monstera', name:'White Monster Monstera', botanical:'Monstera deliciosa cultivar', badge:'Statement plant', tags:['bright','water'], pos:'12%', icon:'✦', care:{watering:'Water when the top 2–3 inches are dry. Soak evenly, then empty the saucer so roots are never left standing in water.', fertilising:'Use a balanced fertiliser at half strength every 2–4 weeks while producing new leaves.', light:'Bright, indirect light is especially important for maintaining its pale variegation. Avoid harsh afternoon sun.', soil:'A chunky aroid mix: houseplant soil with bark, perlite and a little coco coir works beautifully.', spot:'Close to a bright, filtered window, with room to stretch. Rotate it occasionally.', watch:'White areas can scorch in direct sun. Browning, drooping leaves may mean thirst; yellowing can mean overwatering.'}},
  {id:'scindapsus', name:'Scindapsus Exotica', botanical:'Scindapsus pictus', badge:'Easy-going', tags:['easy','bright'], pos:'91%', icon:'⌁', care:{watering:'Let the top half of the pot dry, then water well. It is more forgiving of a brief dry spell than soggy roots.', fertilising:'Feed every 2–4 weeks at half strength during active growth.', light:'Medium to bright indirect light brings out the silver splashes.', soil:'A loose, well-draining aroid mix with bark or perlite.', spot:'Trailing from a bright shelf or climbing a small pole near a filtered window.', watch:'Curling leaves tend to mean it is thirsty. Watch new growth and leaf folds for thrips.'}},
  {id:'money-tree', name:'Money Tree', botanical:'Pachira aquatica', badge:'Easy-going', tags:['easy','water'], pos:'57%', icon:'♧', care:{watering:'Water when the top 2 inches feel dry, then drain it well. It likes consistency rather than extremes.', fertilising:'Half-strength feed every 3–4 weeks during spring through early autumn.', light:'Bright, indirect light. It will tolerate medium light but grow more slowly.', soil:'A well-draining general houseplant mix in a pot with drainage.', spot:'A bright room, a few feet from a sunny window, away from heating or AC blasts.', watch:'Yellow leaves often follow overwatering. A few older leaves dropping now and then is normal.'}},
  {id:'haworthia', name:'Miami Haworthia', botanical:'Haworthiopsis attenuata', badge:'Very easy', tags:['easy'], pos:'40%', icon:'✺', care:{watering:'Let the pot dry fully before watering again. In cooler, darker months this may be only occasionally.', fertilising:'A very light feed every 6–8 weeks in its growing season.', light:'Bright indirect light, or gentle morning sun. It is happier without hot all-day sun.', soil:'Gritty cactus soil with excellent drainage.', spot:'A bright windowsill with softened light, or a bright desk near a window.', watch:'A soft base signals overwatering. Red or bleached leaves suggest it needs softer light.'}},
  {id:'neon-pothos', name:'Neon Pothos', botanical:'Epipremnum aureum', badge:'Easy-going', tags:['easy','water'], pos:'74%', icon:'⌁', care:{watering:'Let the top 1–2 inches dry, then water deeply and let it drain. It will tell you when it is thirsty by gently drooping.', fertilising:'Feed at half strength every 2–4 weeks during active growth.', light:'Medium to bright indirect light preserves the luminous chartreuse color.', soil:'Regular houseplant mix loosened with a handful of perlite.', spot:'A bright shelf, hanging basket, or trailing from a bookcase away from direct afternoon rays.', watch:'Sudden yellow leaves usually mean overwatering. Pale, stretched growth means it would like more light.'}},
  {id:'fernwood', name:'Sansevieria Fernwood', botanical:'Dracaena angolensis', badge:'Very easy', tags:['easy'], pos:'24%', icon:'↟', care:{watering:'Allow the mix to dry completely before a thorough drink. Always pour away excess water.', fertilising:'A half-strength feed every 6–8 weeks in active growth is enough.', light:'Adaptable from medium to bright indirect light. More brightness usually means happier, tidier growth.', soil:'Fast-draining cactus mix in a pot with a drainage hole.', spot:'A bright corner, side table, or window nearby — it is wonderfully unfussy.', watch:'Soft, collapsing stems are the clearest sign of too much water. Keep the crown dry.'}}
];
const customPlantKey='leafday-custom-plants';
const removedPlantKey='leafday-removed-plants';
const plantImages={lipstick:'curly-lipstick-plant','silver-crown':'silver-crown-sansevieria',turtles:'string-of-turtles',bananas:'string-of-bananas',monstera:'white-monster-monstera',scindapsus:'scindapsus-exotica','money-tree':'money-tree',haworthia:'miami-haworthia','neon-pothos':'neon-pothos',fernwood:'sansevieria-fernwood'};
const imageStyle=plant=>plantImages[plant.id]?`--image:url('public/assets/plants/${plantImages[plant.id]}.png')`:'';
const readCustomPlants=()=>{try{return JSON.parse(localStorage.getItem(customPlantKey))||[]}catch{return[]}};
const readRemovedPlants=()=>{try{return JSON.parse(localStorage.getItem(removedPlantKey))||[]}catch{return[]}};
const plants=[...starterPlants.filter(plant=>!readRemovedPlants().includes(plant.id)),...readCustomPlants()];

const icons = {watering:'◒', fertilising:'✦', light:'☼', soil:'◌', spot:'⌂', watch:'!'};
const titles = {watering:'Watering', fertilising:'Fertilising', light:'Light', soil:'Soil', spot:'Best spot', watch:'Watch-outs'};
const safe=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const grid = document.querySelector('#plantGrid'); const dialog = document.querySelector('#plantDialog'); const dialogContent = document.querySelector('#dialogContent');
let activeFilter='all'; let currentPlant=null; let activeSection='watering';

function renderGrid(){ const visible=plants.filter(p=>activeFilter==='all'||p.tags.includes(activeFilter)); document.querySelector('#plantCount').textContent=visible.length; grid.innerHTML=visible.map(p=>`<button class="plant-card" data-id="${p.id}" style="--pos:${p.pos};${imageStyle(p)}"><span class="card-top"><span class="difficulty">${safe(p.badge)}</span><span class="arrow">↗</span></span><span class="card-bottom"><span><h3>${safe(p.name)}</h3><p>${safe(p.botanical)}</p></span></span></button>`).join(''); grid.querySelectorAll('.plant-card').forEach(card=>card.addEventListener('click',()=>openPlant(card.dataset.id))); }
function openPlant(id){ currentPlant=plants.find(p=>p.id===id); activeSection='watering'; renderDetail(); dialog.showModal(); }
function renderDetail(){ const p=currentPlant; const tabs=Object.keys(titles).map(key=>`<button class="care-tab ${activeSection===key?'active':''}" data-section="${key}">${titles[key]}</button>`).join(''); const logs=getLogs(); const log=logs.find(l=>l.plantId===p.id&&l.type===activeSection); const detail=p.care[activeSection]; dialogContent.innerHTML=`<section class="detail-hero" style="--pos:${p.pos};${imageStyle(p)}"><div><p class="eyebrow" style="color:#dceacb">${safe(p.botanical)}</p><h2>${safe(p.name)}</h2><p>${safe(p.badge)} · your plant care guide</p></div></section><section class="care-content"><div class="care-tabs">${tabs}</div><div class="care-panel"><div class="panel-icon">${icons[activeSection]}</div><div><p class="eyebrow">${titles[activeSection]}</p><h3>${sectionHeading(activeSection)}</h3><p>${detail}</p></div></div><div class="future-track"><p><strong>Care tracking is ready when you are.</strong>${log ? `Last ${titles[activeSection].toLowerCase()}: ${new Date(log.date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}` : `Log a ${titles[activeSection].toLowerCase()} to start building this plant's routine.`}</p><button class="log-button ${log?'logged':''}" data-log="${activeSection}">${log?'Logged today ✓':`Log ${titles[activeSection].toLowerCase()}`}</button></div><div class="remove-row"><span>Don’t have this plant anymore?</span><button class="remove-button" type="button">Remove plant</button></div></section>`; dialogContent.querySelectorAll('.care-tab').forEach(t=>t.addEventListener('click',()=>{activeSection=t.dataset.section;renderDetail()})); dialogContent.querySelector('.log-button').addEventListener('click',logCare); dialogContent.querySelector('.remove-button').addEventListener('click',removePlant); }
function sectionHeading(section){ return {watering:'Feel first, then water.',fertilising:'Feed the new growth.',light:'Find its happy glow.',soil:'Give roots room to breathe.',spot:'A place it can settle in.',watch:'A few little things to notice.'}[section]; }
function getLogs(){try{return JSON.parse(localStorage.getItem('leafday-care-log'))||[]}catch{return[]}} function logCare(){const logs=getLogs().filter(l=>!(l.plantId===currentPlant.id&&l.type===activeSection)); logs.unshift({plantId:currentPlant.id,type:activeSection,date:new Date().toISOString()});localStorage.setItem('leafday-care-log',JSON.stringify(logs));renderDetail();}
function removePlant(){const plant=currentPlant;if(!window.confirm(`Remove ${plant.name} and its saved care history?`))return;const index=plants.findIndex(item=>item.id===plant.id);if(index>=0)plants.splice(index,1);localStorage.setItem('leafday-care-log',JSON.stringify(getLogs().filter(log=>log.plantId!==plant.id)));if(plant.id.startsWith('custom-'))localStorage.setItem(customPlantKey,JSON.stringify(readCustomPlants().filter(item=>item.id!==plant.id)));else {const removed=readRemovedPlants();if(!removed.includes(plant.id)){removed.push(plant.id);localStorage.setItem(removedPlantKey,JSON.stringify(removed));}}dialog.close();renderGrid();}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{activeFilter=btn.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===btn));renderGrid();})); document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close()); dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
const historyDialog=document.querySelector('#historyDialog'); document.querySelector('#calendarButton').addEventListener('click',()=>{const logs=getLogs();document.querySelector('#historyContent').innerHTML=logs.length?`<div class="history-list">${logs.map(l=>{const plant=plants.find(p=>p.id===l.plantId);return `<div class="history-item"><strong>${plant.name} · ${titles[l.type]}</strong><span>${new Date(l.date).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span></div>`}).join('')}</div>`:'<p class="empty-history">Nothing logged yet. Open a plant and tap a care activity when you do it — Leafday will keep the date here.</p>';historyDialog.showModal();}); document.querySelector('.close-history').addEventListener('click',()=>historyDialog.close()); historyDialog.addEventListener('click',e=>{if(e.target===historyDialog)historyDialog.close()});

const generalCare={watering:'Check the soil before watering. Give it a thorough drink once the top inch or two feels dry, then let excess water drain.',fertilising:'Feed at half strength every 4–6 weeks while it is making active new growth.',light:'Start in bright, indirect light and observe how the leaves respond. Avoid intense afternoon sun until you know its preference.',soil:'Use a loose, well-draining houseplant mix in a pot with a drainage hole.',spot:'Choose a bright, stable spot away from heating, air-conditioning, and cold draughts.',watch:'Yellow or soft leaves can mean too much water; limp or crispy leaves often mean it is thirsty or wants gentler light.'};
function createProfile(name){const n=name.toLowerCase();let care={...generalCare},badge='New to Leafday',tags=['bright'];if(/snake|sansevieria|haworthia|aloe|cactus|succulent/.test(n)){badge='Very easy';tags=['easy'];care={...generalCare,watering:'Let the potting mix dry out completely before watering thoroughly. Much less often in winter.',fertilising:'Use a light feed every 6–8 weeks while it is actively growing.',soil:'Use a fast-draining cactus or succulent mix in a pot with drainage.',watch:'Soft leaves or stems mean it has stayed too wet. Give the soil more drying time.'};}else if(/pothos|philodendron|monstera|scindapsus|syngonium|aroid/.test(n)){badge='Easy-going';tags=['easy','bright'];care={...generalCare,watering:'Let the top 1–2 inches of soil dry, then water thoroughly and drain away excess.',fertilising:'Feed at half strength every 2–4 weeks during active growth.',soil:'Use an airy aroid mix with houseplant soil, bark, and perlite.',watch:'Yellow leaves can mean too much water. Watch fresh growth and leaf folds for pests.'};}else if(/fern|calathea|maranta|fittonia|prayer/.test(n)){badge='Gentle care';tags=['water'];care={...generalCare,watering:'Keep the mix lightly moist, watering when the surface is just beginning to dry. Do not leave it sitting in water.',light:'Bright to medium indirect light; direct sun can scorch delicate leaves.',watch:'Crisp edges can signal dry air or inconsistent watering. Yellow leaves often mean the mix has stayed wet.'};}return {care,badge,tags};}
const addDialog=document.querySelector('#addPlantDialog');document.querySelector('#addPlantButton').addEventListener('click',()=>{document.querySelector('#plantName').value='';addDialog.showModal();document.querySelector('#plantName').focus();});document.querySelector('.close-add').addEventListener('click',()=>addDialog.close());addDialog.addEventListener('click',e=>{if(e.target===addDialog)addDialog.close()});document.querySelector('#addPlantForm').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#plantName').value.trim();if(!name)return;const newPlant={id:`custom-${Date.now()}`,name,botanical:'Personal plant collection',pos:`${18+(plants.length*13)%72}%`,...createProfile(name)};plants.push(newPlant);const saved=readCustomPlants();saved.push(newPlant);localStorage.setItem(customPlantKey,JSON.stringify(saved));activeFilter='all';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));renderGrid();addDialog.close();openPlant(newPlant.id);}); renderGrid();
