const starterPlants = [
  {id:'lipstick', name:'Curly Lipstick Plant', botanical:'Aeschynanthus radicans', badge:'Easy-going', tags:['easy'], pos:'82%', icon:'⌇', care:{watering:'Water when the top inch of soil feels dry. Keep it lightly and evenly moist in its growing months, but never soggy.', fertilising:'Feed at half strength every 2–4 weeks while it is actively growing. Let a new plant settle in for 2–4 weeks first.', light:'Bright, indirect light keeps the curls full and helps flowers form. A little gentle morning sun is lovely.', soil:'An airy, fast-draining mix. Add orchid bark or perlite to regular houseplant soil.', spot:'Near an east-facing window, or just back from a bright south or west window.', watch:'Crispy leaves usually mean dry air or underwatering; yellow leaves usually mean it stayed too wet.'}},
  {id:'silver-crown', name:'Silver Crown Sansevieria', botanical:'Dracaena trifasciata', badge:'Very easy', tags:['easy'], pos:'65%', icon:'↟', care:{watering:'Let the potting mix dry out completely, then water thoroughly and let excess drain away. Much less often in winter.', fertilising:'A light feed every 6–8 weeks during active growth is plenty.', light:'Flexible and forgiving: low to bright indirect light. Brighter light encourages stronger growth.', soil:'Use a cactus or succulent mix, ideally with extra perlite for fast drainage.', spot:'A few feet from almost any window; avoid a cold, draughty sill.', watch:'Soft or yellowing leaves usually mean too much water. Keep water out of the center of the rosette.'}},
  {id:'turtles', name:'String of Turtles', botanical:'Peperomia prostrata', badge:'Gentle care', tags:['bright'], pos:'49%', icon:'◌', care:{watering:'Water when the upper half of the pot feels dry. Its fine roots dislike both bone-dry soil and sitting wet.', fertilising:'Half-strength feed every 4–6 weeks in the growing season.', light:'Bright, indirect light. Too much sun fades the tiny turtle pattern.', soil:'A small pot of airy, well-draining mix with perlite or bark.', spot:'A bright shelf near an east or filtered south-facing window.', watch:'Sparse vines can mean low light. Mushy stems are a sign to let the mix dry more between waterings.'}},
  {id:'bananas', name:'String of Bananas', botanical:'Curio radicans', badge:'Sun seeker', tags:['easy','bright'], pos:'32%', icon:'⌁', care:{watering:'Allow the soil to dry almost completely, then soak and drain. The banana-shaped leaves hold a little water.', fertilising:'Feed lightly every 4–6 weeks during active growth.', light:'Bright indirect light, with a few hours of gentle sun if it can take it.', soil:'A very fast-draining cactus or succulent blend in a pot with a drainage hole.', spot:'A sunny hanging spot, set just back from a south or west window.', watch:'Transparent or mushy bananas point to overwatering. Long gaps between leaves usually mean it wants more light.'}},
  {id:'monstera', name:'White Monster Monstera', botanical:'Monstera deliciosa cultivar', badge:'Statement plant', tags:['bright','water'], pos:'12%', icon:'✦', care:{watering:'Water when the top 2–3 inches are dry. Soak evenly, then empty the saucer so roots are never left standing in water.', fertilising:'Use a balanced fertiliser at half strength every 2–4 weeks while producing new leaves.', light:'Bright, indirect light is especially important for maintaining its pale variegation. Avoid harsh afternoon sun.', soil:'A chunky aroid mix: houseplant soil with bark, perlite and a little coco coir works beautifully.', spot:'Close to a bright, filtered window, with room to stretch. Rotate it occasionally.', watch:'White areas can scorch in direct sun. Browning, drooping leaves may mean thirst; yellowing can mean overwatering.'}},
  {id:'scindapsus', name:'Scindapsus Exotica', botanical:'Scindapsus pictus', badge:'Easy-going', tags:['easy','bright'], pos:'91%', icon:'⌁', care:{watering:'Let the top half of the pot dry, then water well. It is more forgiving of a brief dry spell than soggy roots.', fertilising:'Feed every 2–4 weeks at half strength during active growth.', light:'Medium to bright indirect light brings out the silver splashes.', soil:'A loose, well-draining aroid mix with bark or perlite.', spot:'Trailing from a bright shelf or climbing a small pole near a filtered window.', watch:'Curling leaves tend to mean it is thirsty. Watch new growth and leaf folds for thrips.'}},
  {id:'money-tree', name:'Money Tree', botanical:'Pachira aquatica', badge:'Easy-going', tags:['easy','water'], pos:'57%', icon:'♧', care:{watering:'Water when the top 2 inches feel dry, then drain it well. It likes consistency rather than extremes.', fertilising:'Half-strength feed every 3–4 weeks during spring through early autumn.', light:'Bright, indirect light. It will tolerate medium light but grow more slowly.', soil:'A well-draining general houseplant mix in a pot with drainage.', spot:'A bright room, a few feet from a sunny window, away from heating or AC blasts.', watch:'Yellow leaves often follow overwatering. A few older leaves dropping now and then is normal.'}},
  {id:'haworthia', name:'Miami Haworthia', botanical:'Haworthiopsis attenuata', badge:'Very easy', tags:['easy'], pos:'40%', icon:'✺', care:{watering:'Let the pot dry fully before watering again. In cooler, darker months this may be only occasionally.', fertilising:'A very light feed every 6–8 weeks in its growing season.', light:'Bright indirect light, or gentle morning sun. It is happier without hot all-day sun.', soil:'Gritty cactus soil with excellent drainage.', spot:'A bright windowsill with softened light, or a bright desk near a window.', watch:'A soft base signals overwatering. Red or bleached leaves suggest it needs softer light.'}},
  {id:'neon-pothos', name:'Neon Pothos', botanical:'Epipremnum aureum', badge:'Easy-going', tags:['easy','water'], pos:'74%', icon:'⌁', care:{watering:'Let the top 1–2 inches dry, then water deeply and let it drain. It will tell you when it is thirsty by gently drooping.', fertilising:'Feed at half strength every 2–4 weeks during active growth.', light:'Medium to bright indirect light preserves the luminous chartreuse color.', soil:'Regular houseplant mix loosened with a handful of perlite.', spot:'A bright shelf, hanging basket, or trailing from a bookcase away from direct afternoon rays.', watch:'Sudden yellow leaves usually mean overwatering. Pale, stretched growth means it would like more light.'}},
  {id:'fernwood', name:'Sansevieria Fernwood', botanical:'Dracaena angolensis', badge:'Very easy', tags:['easy'], pos:'24%', icon:'↟', care:{watering:'Allow the mix to dry completely before a thorough drink. Always pour away excess water.', fertilising:'A half-strength feed every 6–8 weeks in active growth is enough.', light:'Adaptable from medium to bright indirect light. More brightness usually means happier, tidier growth.', soil:'Fast-draining cactus mix in a pot with a drainage hole.', spot:'A bright corner, side table, or window nearby — it is wonderfully unfussy.', watch:'Soft, collapsing stems are the clearest sign of too much water. Keep the crown dry.'}},
  {id:'irish-spider', name:'Irish Spider Plant', botanical:'Chlorophytum comosum ‘Irish’', badge:'Easy-going', tags:['easy'], pos:'38%', icon:'⌁', care:{watering:'Water when the top inch of soil feels dry. Give it a thorough drink, let the excess drain, and reduce watering slightly during winter. Avoid leaving the pot standing in water.', fertilising:'Feed lightly with a balanced liquid fertiliser every 6–8 weeks during spring and summer. Skip feeding during slower winter growth.', light:'Bright, indirect light keeps its colouring crisp and growth full. It tolerates lower light, but grows more slowly; strong direct sun can scorch the leaves.', soil:'Use a loose, well-draining houseplant mix in a pot with drainage holes. Repot when its thick roots become tightly crowded.', spot:'A bright shelf or hanging planter near an east- or north-facing window, away from radiators and harsh afternoon sun.', watch:'Brown tips may be caused by inconsistent watering, dry air, strong sun, or minerals in tap water. Filtered or rainwater can help. Pale, limp foliage usually means it needs a drink.'}},
  {id:'dwarf-elephant', name:'Dwarf Elephant’s Food Jade', botanical:'Portulacaria afra — dwarf form', badge:'Very easy', tags:['easy','bright'], pos:'51%', icon:'♧', care:{watering:'Let the soil dry thoroughly before watering deeply, then allow all excess water to escape. Water much less during winter, especially in a cool or dim room.', fertilising:'Feed monthly at half strength during active spring and summer growth. Do not fertilise when the plant is resting in winter.', light:'Give it plenty of bright light and several hours of gentle direct sun if possible. Acclimate it gradually before moving it into stronger sunlight.', soil:'Use a gritty cactus or succulent mix with generous pumice, grit, or perlite. A drainage hole is essential.', spot:'Close to a bright south-, west-, or east-facing window. Rotate occasionally to maintain balanced, compact growth.', watch:'Soft, yellowing leaves or stems usually indicate excess moisture. Wrinkled lower leaves signal thirst. Watch the stems and leaf joints for mealybugs.'}},
  {id:'rhipsalis-clavata', name:'Rhipsalis Clavata', botanical:'Rhipsalis clavata', badge:'Gentle care', tags:['bright','water'], pos:'64%', icon:'⌇', care:{watering:'Water when the upper portion of the mix begins to dry, then drain thoroughly. Keep it a little more evenly moist than a desert cactus, but never continuously wet. Reduce watering in winter.', fertilising:'Apply a dilute, low-nitrogen fertiliser about monthly during active growth. Pause or greatly reduce feeding in winter.', light:'Bright, indirect light or softly filtered morning sun is ideal. Protect the trailing stems from intense midday and afternoon sun.', soil:'Use an airy epiphytic-cactus mix containing bark, perlite or pumice, and a little moisture-retentive potting mix.', spot:'A hanging planter near a bright east-facing window, where its stems have room to trail and receive good airflow.', watch:'Wrinkled stems can indicate thirst, while soft or darkened stems suggest excess water and possible rot. Dry brown tips may mean low humidity. Check regularly for mealybugs.'}},
  {id:'brazilian-heart', name:'Brazilian Heart Ivy', botanical:'Philodendron hederaceum ‘Brasil’', badge:'Easy-going', tags:['easy','bright','water'], pos:'77%', icon:'⌁', care:{watering:'Water when the top inch or two of soil feels dry. Soak the mix evenly, allow it to drain, and never leave the pot standing in water.', fertilising:'Feed at half strength once or twice a month during active spring and summer growth. Reduce feeding when growth slows.', light:'Medium to bright indirect light is best. Brighter indirect light maintains the yellow-green variegation, while harsh direct sun can scorch it.', soil:'Use a loose, well-draining aroid mix containing houseplant soil, orchid bark, and perlite.', spot:'Trail it from a bright shelf or hanging basket, or let it climb near an east- or filtered south-facing window.', watch:'Yellow leaves commonly indicate soil staying too wet. Small, widely spaced leaves or fading variegation suggest insufficient light. Check new growth and leaf undersides for spider mites, thrips, and mealybugs.'}}
];
const customPlantKey='leafday-custom-plants';
const removedPlantKey='leafday-removed-plants';
const plantImages={lipstick:'curly-lipstick-plant','silver-crown':'silver-crown-sansevieria',turtles:'string-of-turtles',bananas:'string-of-bananas',monstera:'white-monster-monstera',scindapsus:'scindapsus-exotica','money-tree':'money-tree',haworthia:'miami-haworthia','neon-pothos':'neon-pothos',fernwood:'sansevieria-fernwood','irish-spider':'irish-spider-plant','dwarf-elephant':'dwarf-elephants-food-jade','rhipsalis-clavata':'rhipsalis-clavata','brazilian-heart':'brazilian-heart-ivy'};
const imageStyle=plant=>plant.image?`--image:url("${plant.image}")`:plantImages[plant.id]?`--image:url('public/assets/plants/${plantImages[plant.id]}.png')`:'';
const readCustomPlants=()=>{try{return JSON.parse(localStorage.getItem(customPlantKey))||[]}catch{return[]}};
const readRemovedPlants=()=>{try{return JSON.parse(localStorage.getItem(removedPlantKey))||[]}catch{return[]}};
const plants=[...starterPlants.filter(plant=>!readRemovedPlants().includes(plant.id)),...readCustomPlants()];

const icons = {watering:'◒', fertilising:'✦', light:'☼', soil:'◌', spot:'⌂', watch:'!'};
const titles = {watering:'Watering', fertilising:'Fertilising', light:'Light', soil:'Soil', spot:'Best spot', watch:'Watch-outs'};
const safe=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const grid = document.querySelector('#plantGrid'); const dialog = document.querySelector('#plantDialog'); const dialogContent = document.querySelector('#dialogContent');
let activeFilter='all'; let currentPlant=null; let activeSection='watering';

function renderGrid(){ const visible=plants.filter(p=>activeFilter==='all'||p.tags.includes(activeFilter)); document.querySelector('#plantCount').textContent=visible.length; grid.innerHTML=visible.map(p=>`<button class="plant-card" data-id="${p.id}" style="--pos:${p.pos};${imageStyle(p)}"><span class="card-top"><span class="difficulty">${safe(p.badge)}</span><span class="arrow">↗</span></span><span class="card-bottom"><span><h3>${safe(p.name)}</h3><p>${safe(p.botanical)}</p></span></span></button>`).join(''); grid.querySelectorAll('.plant-card').forEach(card=>card.addEventListener('click',()=>openPlant(card.dataset.id))); }
function openPlant(id){ currentPlant=plants.find(p=>p.id===id); activeSection='watering'; renderDetail(); dialog.showModal(); }
function renderDetail(){ const p=currentPlant; const tabs=Object.keys(titles).map(key=>`<button class="care-tab ${activeSection===key?'active':''}" data-section="${key}">${titles[key]}</button>`).join(''); const logs=getLogs(); const log=logs.find(l=>l.plantId===p.id&&l.type===activeSection); const detail=p.care[activeSection]; dialogContent.innerHTML=`<section class="detail-hero" style="--pos:${p.pos};${imageStyle(p)}"><div><p class="eyebrow" style="color:#dceacb">${safe(p.botanical)}</p><h2>${safe(p.name)}</h2><p>${safe(p.badge)} · your plant care guide</p></div></section><section class="care-content"><div class="care-tabs">${tabs}</div><div class="care-panel"><div class="panel-icon">${icons[activeSection]}</div><div><p class="eyebrow">${titles[activeSection]}</p><h3>${sectionHeading(activeSection)}</h3><p>${safe(detail)}</p></div></div><div class="future-track"><p><strong>Care tracking is ready when you are.</strong>${log ? `Last ${titles[activeSection].toLowerCase()}: ${new Date(log.date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}` : `Log a ${titles[activeSection].toLowerCase()} to start building this plant's routine.`}</p><button class="log-button ${log?'logged':''}" data-log="${activeSection}">${log?'Logged today ✓':`Log ${titles[activeSection].toLowerCase()}`}</button></div><div class="remove-row"><span>Don’t have this plant anymore?</span><button class="remove-button" type="button">Remove plant</button></div></section>`; dialogContent.querySelectorAll('.care-tab').forEach(t=>t.addEventListener('click',()=>{activeSection=t.dataset.section;renderDetail()})); dialogContent.querySelector('.log-button').addEventListener('click',logCare); dialogContent.querySelector('.remove-button').addEventListener('click',removePlant); }
function sectionHeading(section){ return {watering:'Feel first, then water.',fertilising:'Feed the new growth.',light:'Find its happy glow.',soil:'Give roots room to breathe.',spot:'A place it can settle in.',watch:'A few little things to notice.'}[section]; }
function getLogs(){try{return JSON.parse(localStorage.getItem('leafday-care-log'))||[]}catch{return[]}} function logCare(){const logs=getLogs().filter(l=>!(l.plantId===currentPlant.id&&l.type===activeSection)); logs.unshift({plantId:currentPlant.id,type:activeSection,date:new Date().toISOString()});localStorage.setItem('leafday-care-log',JSON.stringify(logs));renderDetail();}
function removePlant(){const plant=currentPlant;if(!window.confirm(`Remove ${plant.name} and its saved care history?`))return;const index=plants.findIndex(item=>item.id===plant.id);if(index>=0)plants.splice(index,1);localStorage.setItem('leafday-care-log',JSON.stringify(getLogs().filter(log=>log.plantId!==plant.id)));if(plant.id.startsWith('custom-'))localStorage.setItem(customPlantKey,JSON.stringify(readCustomPlants().filter(item=>item.id!==plant.id)));else {const removed=readRemovedPlants();if(!removed.includes(plant.id)){removed.push(plant.id);localStorage.setItem(removedPlantKey,JSON.stringify(removed));}}dialog.close();renderGrid();}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{activeFilter=btn.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===btn));renderGrid();})); document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close()); dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
const historyDialog=document.querySelector('#historyDialog'); document.querySelector('#calendarButton').addEventListener('click',()=>{const logs=getLogs();document.querySelector('#historyContent').innerHTML=logs.length?`<div class="history-list">${logs.map(l=>{const plant=plants.find(p=>p.id===l.plantId);return `<div class="history-item"><strong>${plant.name} · ${titles[l.type]}</strong><span>${new Date(l.date).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</span></div>`}).join('')}</div>`:'<p class="empty-history">Nothing logged yet. Open a plant and tap a care activity when you do it — Leafday will keep the date here.</p>';historyDialog.showModal();}); document.querySelector('.close-history').addEventListener('click',()=>historyDialog.close()); historyDialog.addEventListener('click',e=>{if(e.target===historyDialog)historyDialog.close()});

const generalCare={watering:'Check the soil before watering. Give it a thorough drink once the top inch or two feels dry, then let excess water drain.',fertilising:'Feed at half strength every 4–6 weeks while it is making active new growth.',light:'Start in bright, indirect light and observe how the leaves respond. Avoid intense afternoon sun until you know its preference.',soil:'Use a loose, well-draining houseplant mix in a pot with a drainage hole.',spot:'Choose a bright, stable spot away from heating, air-conditioning, and cold draughts.',watch:'Yellow or soft leaves can mean too much water; limp or crispy leaves often mean it is thirsty or wants gentler light.'};
function createProfile(name){const n=name.toLowerCase();let care={...generalCare},badge='New to Leafday',tags=['bright'];if(/snake|sansevieria|haworthia|aloe|cactus|succulent/.test(n)){badge='Very easy';tags=['easy'];care={...generalCare,watering:'Let the potting mix dry out completely before watering thoroughly. Much less often in winter.',fertilising:'Use a light feed every 6–8 weeks while it is actively growing.',soil:'Use a fast-draining cactus or succulent mix in a pot with drainage.',watch:'Soft leaves or stems mean it has stayed too wet. Give the soil more drying time.'};}else if(/pothos|philodendron|monstera|scindapsus|syngonium|aroid/.test(n)){badge='Easy-going';tags=['easy','bright'];care={...generalCare,watering:'Let the top 1–2 inches of soil dry, then water thoroughly and drain away excess.',fertilising:'Feed at half strength every 2–4 weeks during active growth.',soil:'Use an airy aroid mix with houseplant soil, bark, and perlite.',watch:'Yellow leaves can mean too much water. Watch fresh growth and leaf folds for pests.'};}else if(/fern|calathea|maranta|fittonia|prayer/.test(n)){badge='Gentle care';tags=['water'];care={...generalCare,watering:'Keep the mix lightly moist, watering when the surface is just beginning to dry. Do not leave it sitting in water.',light:'Bright to medium indirect light; direct sun can scorch delicate leaves.',watch:'Crisp edges can signal dry air or inconsistent watering. Yellow leaves often mean the mix has stayed wet.'};}return {care,badge,tags};}
const addDialog=document.querySelector('#addPlantDialog');
const addForm=document.querySelector('#addPlantForm');
const careFields=document.querySelector('#careFields');
const photoInput=document.querySelector('#plantPhoto');
const photoPreview=document.querySelector('#photoPreview');
let pendingPhoto='';
careFields.innerHTML=Object.keys(titles).map(key=>`<label for="care-${key}">${titles[key]}<textarea id="care-${key}" name="${key}" required maxlength="500"></textarea></label>`).join('');
function fillCareFields(name=''){const profile=createProfile(name);Object.keys(titles).forEach(key=>{document.querySelector(`#care-${key}`).value=profile.care[key]});return profile;}
function resetAddForm(){addForm.reset();careFields.querySelectorAll('textarea').forEach(field=>delete field.dataset.edited);pendingPhoto='';photoPreview.removeAttribute('style');photoPreview.textContent='＋';document.querySelector('#formError').textContent='';fillCareFields();}
function resizePhoto(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Please choose a JPG, PNG or WebP image.'));if(file.size>12*1024*1024)return reject(new Error('Please choose an image smaller than 12 MB.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('That photo could not be read.'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('That photo format is not supported.'));img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.82));};img.src=reader.result;};reader.readAsDataURL(file);});}
document.querySelector('#addPlantButton').addEventListener('click',()=>{resetAddForm();addDialog.showModal();document.querySelector('#plantName').focus();});
document.querySelector('#plantName').addEventListener('blur',e=>{if(e.target.value.trim()&&!Array.from(addForm.elements).some(el=>el.tagName==='TEXTAREA'&&el.dataset.edited==='true'))fillCareFields(e.target.value.trim());});
careFields.addEventListener('input',e=>{if(e.target.tagName==='TEXTAREA')e.target.dataset.edited='true';});
photoInput.addEventListener('change',async()=>{const file=photoInput.files[0];if(!file){pendingPhoto='';return}try{pendingPhoto=await resizePhoto(file);photoPreview.textContent='';photoPreview.style.backgroundImage=`url("${pendingPhoto}")`;document.querySelector('#formError').textContent='';}catch(error){photoInput.value='';pendingPhoto='';document.querySelector('#formError').textContent=error.message;}});
document.querySelector('.close-add').addEventListener('click',()=>addDialog.close());addDialog.addEventListener('click',e=>{if(e.target===addDialog)addDialog.close()});
addForm.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(addForm);const name=String(data.get('plantName')).trim();if(!name)return;const tags=data.getAll('plantTag');const care=Object.fromEntries(Object.keys(titles).map(key=>[key,String(data.get(key)).trim()]));const profile=createProfile(name);const newPlant={id:`custom-${Date.now()}`,name,botanical:String(data.get('botanicalName')).trim()||'Personal plant collection',badge:tags.includes('easy')?'Easy-going':tags.includes('water')?'Thirsty':'Personal care',tags:tags.length?tags:profile.tags,pos:`${18+(plants.length*13)%72}%`,care,...(pendingPhoto?{image:pendingPhoto}:{})};const saved=readCustomPlants();saved.push(newPlant);try{localStorage.setItem(customPlantKey,JSON.stringify(saved));}catch{document.querySelector('#formError').textContent='There isn’t enough browser storage for this photo. Try a smaller image.';return}plants.push(newPlant);activeFilter='all';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'));renderGrid();addDialog.close();openPlant(newPlant.id);}); renderGrid();
